//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkBarsOtchet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumables()
        {
            this.Repair_Order = new HashSet<Repair_Order>();
        }
    
        public int Id_Con { get; set; }
        public string Repair_or_Modern { get; set; }
        public string Name { get; set; }
        public string Serial_Number { get; set; }
        public string BY_or_NEW { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Order> Repair_Order { get; set; }
    }
}
