//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkBarsOtchet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_of_Fixed_Assets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object_of_Fixed_Assets()
        {
            this.Repair_Order = new HashSet<Repair_Order>();
        }
    
        public int Id_Object { get; set; }
        public string Name_Obj { get; set; }
        public string Inventory_Number { get; set; }
        public Nullable<decimal> Replacement_Cost { get; set; }
        public string Actual_Service_Life { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Order> Repair_Order { get; set; }
    }
}
