//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkBarsOtchet.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Repair_Order = new HashSet<Repair_Order>();
        }
    
        public int Id_User { get; set; }
        public string FIO { get; set; }
        public int S_Id_Post { get; set; }
        public int S_Id_Division { get; set; }
        public string Login_User { get; set; }
        public string Password_User { get; set; }
        public Nullable<bool> isSup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Order> Repair_Order { get; set; }
        public virtual S_Divisions S_Divisions { get; set; }
        public virtual S_Posts S_Posts { get; set; }
    }
}
